#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# prompt
function nix_prompt () {
  if [ "$IN_NIX_SHELL" -eq "1" ]; then
    echo -n "%F{red}[$name]%f "
  fi
}
export PROMPT="$(nix_prompt)$PROMPT"

